version: "3.8"
services:
  lumen-api:
    build: ./lumen
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=mydb
      - DB_USERNAME=root
      - DB_PASSWORD=root

  node-api:
    build: ./node
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - lumen-api
    environment:
      - LUMEN_API_URL=http://lumen-api:8000
      - REDIS_HOST=redis

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - node-api
