version: "3.8"

services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    networks:
      - my_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10
      timeout: 5s

  lumen-api:
    build: ./backend/lumen-api
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_DATABASE: mydb
      DB_USERNAME: root
      DB_PASSWORD: root
    restart: always
    networks:
      - my_network

  node-api:
    build: ./backend/node-api
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - lumen-api
    environment:
      - LUMEN_API_URL=http://lumen-api:8000
      - REDIS_HOST=redis
    networks:
      - my_network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - node-api
    networks:
      - my_network

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
